# Development Environment Configuration
# This file contains configuration specific to the
# development environment.
# Used for:
# - Local development
# - Debugging and testing features
# - Developer-friendly settings

server:
  port: 8083

# database connection
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth_app
    username: root
    password: 1234

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernates:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect