# Development Environment Configuration
# This file contains configuration specific to the
# development environment.
# Used for:
# - Local development
# - Debugging and testing features
# - Developer-friendly settings

server:
  port: 8083

# database connection
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth_app?useSSL=false&serverTimezone=UTC
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:1234}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

security:
  jwt:
    secret: ${JWT_SECRET:eijefvhdsjhaq73275y4rhjfdkskhw2387hkwsdhgw7}
    issuer: ${JWT_ISSUER:com.sadcodes.authapp}

    access-ttl-seconds: ${JWT_ACCESS_TTL_SECONDS:3600}
    refresh-ttl-seconds: ${JWT_REFRESH_TTL_SECONDS:86400}

    refresh-token-cookie-name: ${JWT_REFRESH_COOKIE_NAME:refreshToken}

    cookie-secure: ${JWT_COOKIE_SECURE:false}
    cookie-http-only: ${JWT_COOKIE_HTTP_ONLY:true}
    cookie-same-site: ${JWT_COOKIE_SAME_SITE:Lax}

