server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth_app?useSSL=false&serverTimezone=UTC
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:1234}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
#        dialect: org.hibernate.dialect.MySQL8Dialect
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            # /login/oauth2/code/google
            scope:
              - email
              - profile
              - openid
          github:
            client-id: ${GITHUB_CLIENT_ID}
            client-secret: ${GITHUB_CLIENT_SECRET}
            # /login/oauth2/code/github
            scope:
              - user:email
              - read:user

security:
  jwt:
    secret: ${JWT_SECRET:abcdefghijklmnopqrstuvwxyz0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZ1234567890}
    issuer: ${JWT_ISSUER:com.sadcodes.authapp}

    access-ttl-seconds: ${JWT_ACCESS_TTL_SECONDS:3600}
    refresh-ttl-seconds: ${JWT_REFRESH_TTL_SECONDS:86400}

    refresh-token-cookie-name: ${JWT_REFRESH_COOKIE_NAME:refreshToken}

    cookie-secure: ${JWT_COOKIE_SECURE:false}
    cookie-http-only: ${JWT_COOKIE_HTTP_ONLY:true}
    cookie-same-site: ${JWT_COOKIE_SAME_SITE:Lax}
    cookie-domain: ${JWT_COOKIE_DOMAIN:}

app:
  auth:
    frontend:
      success-redirect: http://localhost:5173/auth/success
      failure-redirect: http://localhost:5173/auth/failure